### ISSUE TITLE
does it work in ps2?

### ISSUE THREAD

**Issue by lucasmz1** [brad-lin/FreePSXBoot#127]
Hello. I have a ps2 that I am currently using free mcboot, and I want to install your memory card images on a sd card on mx4sio, is it possible ? if it's possible how do I handle it ?
thank you!

**Comment by alex-free** [comment]
> Hello. I have a ps2 that I am currently using free mcboot, and I want to install your memory card images on a sd card on mx4sio, is it possible ? if it's possible how do I handle it ?
> 
> thank you!

Running on a PS2, it does not work. You might be able to install it on a PS2 and then use said memory card on a PS1.
