### ISSUE TITLE
List of BIOS-versions to be confirmed on hardware?

### ISSUE THREAD

**Issue by hurda** [brad-lin/FreePSXBoot#38]
Hello.
In the latest README-change a sentence was added that not all BIOS-versions were tested on hardware but only with an emulator.
Is there a list of those versions still waiting to be confirmed on hardware?
THanks.

**Comment by brad-lin** [comment]
The latest images are slightly different from the previous ones, so they should work as the previous ones, but testing is the only way to know for sure.

I've tested on my 9002 (BIOS 4.1), any other contribution is welcome. Different revisions may have different behaviours, so it's interesting to have several confirmations.

**Comment by hurda** [comment]
Alright, thanks.

**Comment by C1fer** [comment]
It works on my 101 (BIOS 4.5), but I'm having some issues on version 1.1. v1.0 works great though.
