### ISSUE TITLE
Are BIOS 4.0 or SCPH-7000W incompatible or covered by 4.1?

### ISSUE THREAD

**Issue by hurda** [brad-lin/FreePSXBoot#40]
Just noticed that BIOS 4.0 (ps-40j) and SCPH-7000W (ps-41a(w)) are absent from the list.
Or can the 4.1-image be used with them?

1997-08-18
🇯🇵
ps-40j
SCPH-7000, SCPH-7500, SCPH-9000
ec541cd0
8e4c14f567745eff2f0408c8129f72a6

1997-11-14
🇺🇸
ps-41a(w)
SCPH-7000W
b7c43dad
b84be139db3ee6cbd075630aa20a6553

**Comment by brad-lin** [comment]
They are supported now, check the last commit.

Can you test the images on real hardware?

**Comment by hurda** [comment]
No, sorry, just noticed that they were missing in the list.
