### ISSUE TITLE
Installing FreePSXBoot via UNIROM Menu

### ISSUE THREAD

**Issue by Thad-Supersperm** [brad-lin/FreePSXBoot#47]
I noticed in UNIROM 8.0.F there is an item called "Install UNIROM". When I go to it, there is "Install FreePSXBoot to MemCard".
Upon selecting it, it says: "Waiting for CD to become ready & unlocked... Not a valid CD or the drive is locked"
The console is a 9002 and the drive is unlocked. What CD is it talking about?
Thanks.

**Comment by JonathanDotCel** [comment]
Hi @Thad-Supersperm, it's asking for the unirom boot disc which has the memcard images on it.

I'll make this clearer in the next release, thanks :)

**Comment by Thad-Supersperm** [comment]
Thank you for the fast response.
