### ISSUE TITLE
SCPH-5502 not working with 20210421

### ISSUE THREAD

**Issue by mjh17474** [brad-lin/FreePSXBoot#56]
I have reformatted my cheapy Aliexpress memory card that I was using for TonyHax using MCA v2 on a ps2 (SCPH 50003). I performed a full format, selected to restore an image and used 'freepsxboot-unirom-fastload-20210421-bios-3.0-19970106.mcr'.
I boot the PSX with the lid open, select the memory card manager and it just opens as normal. If I put the card back in to the PS2, MCA will see it and format it without a problem (I've tried full and fast).  I tried the same process 3 times just to make sure it didn't work. I then booted an original copy of Tony Hawks 3 and started a new career with the FreePSXBoot card in slot 1 (to see what it would do if I tried to save a career). It detects the card as unformatted, asks me if I'd like to format it and saves the game, I can see the saved game block on the card after. I then tried to create the FreePSXBoot card again with MCA and the result is the same.

**Comment by hurda** [comment]
Some third-party cards behave differently than the Sony-card, especially with regard to FreePSXBoot.
There are reports in here about FreePSXBoot working on a 5502, so it's probably your card that's the problem. Can you somehow get access to a Sony-card and try it with that?

**Comment by mjh17474** [comment]
I'll see if I can grab one off ebay, just wanted to check I wasn't doing something stupid ;)

**Comment by invaderlex** [comment]
That is what was happening to me with a model 1001, try to use other images, try the other 3.0, and some new or older bios versions. I was able to use a 3.0 image in a 1001 with a 2.2 bios. 

https://github.com/brad-lin/FreePSXBoot/issues/50#

**Comment by mjh17474** [comment]
Ok, I've just tried from 2.1 through to 4.1. None of them worked. I also tried a second new cheapy AliExpress card and it did the same thing. I've got an official Sony card on the way, hopefully that will work. :)

**Comment by Ichisuke83** [comment]
I've noticed you said ".mcr". Did you convert or open the .mcd file with some memory card program? If that's the case you can just flash the .mcd file directly in MCA. Otherwise it's probably a bad memory card. I think that some cheap cards can't even hold all 15 blocks....

**Comment by mjh17474** [comment]
I just renamed the .mcd file so it was recognised by MCA. I agree about the cards though. I will know more when my official Sony one arrives.

**Comment by Ichisuke83** [comment]
Pretty sure it is definitely the card. If you can you could try testing it by completely filling the memory card with saves and see what happens. With cheap/bad one you should lose the saves or the card could stop working or whatever.

**Comment by brad-lin** [comment]
This sounds like a bad memory card indeed. Try to read it back using MCA, and post the image here.

**Comment by mjh17474** [comment]
Here  you go. This was the after using the file for a 5502 machine.
[memorycard0.zip](https://github.com/brad-lin/FreePSXBoot/files/6405784/memorycard0.zip)

**Comment by brad-lin** [comment]
The image is full of 0s, i.e. it is either defective or the device writing it is defective. A new memcard should fix it.
