### ISSUE TITLE
Scph 102 not working

### ISSUE THREAD

**Issue by diamondhands97** [brad-lin/FreePSXBoot#61]
I did every step and when I press X on memory card it just enter in the memory card, doesn't boot psxboot

**Comment by diamondhands97** [comment]
already tried the 2 options to the scph 102 and nothing

**Comment by diamondhands97** [comment]
tried on a scph 3500 and the same issue

**Comment by diamondhands97** [comment]
Everytime I do the restore image and reboot the ps2, I don't get the soft crash, I go to the browser and press X on the psxboot memory card and it says it needs to be formated

**Comment by diamondhands97** [comment]
already know the problem, I bought memory cards from aliexpress, they work normaly but doesn't work for the mod

**Comment by faissaloo** [comment]
@diamondhands97 Open up the memory card and check if the EEPROM is a 128kb chip, alot of those cheap memory cards skimp out on the flash and use 64kb chips instead

**Comment by diamondhands97** [comment]
> @diamondhands97 Open up the memory card and check if the EEPROM is a 128kb chip, alot of those cheap memory cards skimp out on the flash and use 64kb chips instead which causes corruption when you try to write a whole memory card image

you´re right
