### ISSUE TITLE
Medievil 2 PAL save file corrupted on Memory card 1

### ISSUE THREAD

**Issue by Ichisuke83** [brad-lin/FreePSXBoot#81]
Using Unirom with freepsxboot on Memory Card in slot 2, Medievil 2 won't allow you to load the save file from memory card 1, telling you that the save file is corrupted while is not.
I'm using latest 8.0.J version.
Medievil 2 is PAL version.
Game works and load save file just fine if boot with Unirom through an action replay cartridge or other methods. So I think there is something wrong with how Freepsxboot disable slot 2.

**Comment by brad-lin** [comment]
What is your BIOS version? I have an updated patch which should fix such issues, it would be great if you could try it and give feedback.

**Comment by Ichisuke83** [comment]
> What is your BIOS version? I have an updated patch which should fix such issues, it would be great if you could try it and give feedback.

Oh I can test this on a 102 with 4.4 Bios, on a 7502, 5502 and 1002.

**Comment by brad-lin** [comment]
Ok, you can try this on the 7502: https://github.com/brad-lin/FreePSXBoot/files/8310007/freepsxboot-unirom-fastload-20220318-bios-4.1-1997-12-16-A-502224b6-slot2.zip

**Comment by Ichisuke83** [comment]
> Ok, you can try this on the 7502: https://github.com/brad-lin/FreePSXBoot/files/8310007/freepsxboot-unirom-fastload-20220318-bios-4.1-1997-12-16-A-502224b6-slot2.zip

Yes. This works fine. So I suppose you have to update all the versions...?

**Comment by brad-lin** [comment]
Nice, thanks for testing. This new version will be released soon (in the coming days), the updated images will be uploaded first in the repo.

**Comment by Ichisuke83** [comment]
> Nice, thanks for testing. This new version will be released soon (in the coming days), the updated images will be uploaded first in the repo.

Sorry, is there a date on when the new version will be released? Otherwise can I have a version for the SCPH 102 4.4 BIOS? Thanks.

**Comment by brad-lin** [comment]
> > Nice, thanks for testing. This new version will be released soon (in the coming days), the updated images will be uploaded first in the repo.
> 
> Sorry, is there a date on when the new version will be released? Otherwise can I have a version for the SCPH 102 4.4 BIOS? Thanks.

I have just pushed the new images for all BIOS versions (no release yet, but the images are available from the links in the readme). Feedback is welcome, thanks.

**Comment by Ichisuke83** [comment]
Thanks!
