### ISSUE TITLE
Spyro 3 backup fails (antipiracy screen) on unmodded 7501 + FreePSXBoot

### ISSUE THREAD

**Issue by paulocode** [brad-lin/FreePSXBoot#98]
https://imgur.com/a/eCMTrPh

I burned an NTSC-U image of Spyro 3 and used FreePSXBoot to run it. On my unmodded SCPH-9002 it runs fine. But on the SCPH-7501 (also unmodded, also using FreePSXBoot), I get the anti piracy screen. What am I missing?

NTSC version of Spyro does not have libcrypt protection according to some web searches..

**Comment by M4x1mumReZ** [comment]
If you're using a PAL console then American and Japanese APv2 games sometimes will or will not activate the AP measures. Whereas if you're using a European APv2 game, then the AP screen will most definitely show.

**Comment by M4x1mumReZ** [comment]
I doubt that Spyro 3 will get AP fixes since it has additional protection that triggers if the memory or disc contents were modified.

**Comment by paulocode** [comment]
Hi @M4x1mumReZ, I was using an NTSC-U game on an NTSC-U console. It seems that when the regions match, it will trigger the modchip check. Anyway I just installed a real modchip instead.
